# Generated by Django 5.1.7 on 2025-03-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("report_date", models.DateField(auto_now_add=True)),
                (
                    "total_donations",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("expenses", models.DecimalField(decimal_places=2, max_digits=12)),
                ("net_balance", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
