# Generated by Django 5.1.7 on 2025-03-24 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalIntake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("animal_id", models.CharField(max_length=12, unique=True)),
                ("species", models.CharField(max_length=50)),
                ("breed", models.CharField(max_length=50)),
                ("age", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=10,
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                ("markings", models.TextField(blank=True, null=True)),
                ("health_status", models.TextField()),
                ("temperament", models.CharField(max_length=100)),
                ("history", models.TextField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("stray", "Stray"),
                            ("surrender", "Owner Surrender"),
                            ("transfer", "Transferred"),
                            ("rescue", "Rescue"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="intakes/photos/"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="intakes/videos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
