# Generated by Django 5.1.7 on 2025-03-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0002_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="adoption_success_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="has_yard",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="home_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_profile_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="pet_experience",
            field=models.BooleanField(default=False),
        ),
    ]
