# Generated by Django 5.1.7 on 2025-03-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0002_animalintake"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animalintake",
            name="source",
            field=models.CharField(
                choices=[
                    ("stray", "Stray"),
                    ("surrender", "Owner Surrender"),
                    ("transfer", "Transferred"),
                    ("rescue", "Rescue"),
                ],
                max_length=50,
            ),
        ),
    ]
