# Generated by Django 5.1.7 on 2025-03-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0002_adoptionrequest_animalimage_donation_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="home_verification_document",
            field=models.FileField(
                blank=True, null=True, upload_to="home_verifications/"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
