# Generated by Django 5.1.7 on 2025-03-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0003_alter_animalintake_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animalintake",
            name="age",
        ),
        migrations.RemoveField(
            model_name="animalintake",
            name="breed",
        ),
        migrations.RemoveField(
            model_name="animalintake",
            name="color",
        ),
        migrations.RemoveField(
            model_name="animalintake",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="animalintake",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="animalintake",
            name="health_status",
        ),
        migrations.RemoveField(
            model_name="animalintake",
            name="history",
        ),
        migrations.RemoveField(
            model_name="animalintake",
            name="markings",
        ),
        migrations.RemoveField(
            model_name="animalintake",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="animalintake",
            name="sex",
        ),
        migrations.RemoveField(
            model_name="animalintake",
            name="source",
        ),
        migrations.RemoveField(
            model_name="animalintake",
            name="species",
        ),
        migrations.RemoveField(
            model_name="animalintake",
            name="temperament",
        ),
        migrations.RemoveField(
            model_name="animalintake",
            name="video",
        ),
        migrations.AlterField(
            model_name="animalintake",
            name="animal_id",
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
