# Generated by Django 5.1.7 on 2025-03-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0003_profile_adoption_success_count_profile_has_yard_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="temperament",
            field=models.CharField(
                choices=[
                    ("Friendly", "Friendly"),
                    ("Aggressive", "Aggressive"),
                    ("Shy", "Shy"),
                    ("Playful", "Playful"),
                ],
                default="Friendly",
                max_length=50,
            ),
        ),
    ]
