# Generated by Django 5.1.7 on 2025-03-24 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0004_remove_animalintake_age_remove_animalintake_breed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animalintake",
            name="age",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="animalintake",
            name="breed",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="animalintake",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="animalintake",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="animalintake",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="animalintake",
            name="health_status",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="animalintake",
            name="history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="animalintake",
            name="markings",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="animalintake",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="intakes/photos/"),
        ),
        migrations.AddField(
            model_name="animalintake",
            name="photos",
            field=models.ImageField(blank=True, null=True, upload_to="animal_photos/"),
        ),
        migrations.AddField(
            model_name="animalintake",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("unknown", "Unknown"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="animalintake",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("stray", "Stray"),
                    ("surrender", "Owner Surrender"),
                    ("transfer", "Transferred"),
                    ("rescue", "Rescue"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="animalintake",
            name="species",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="animalintake",
            name="temperament",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="animalintake",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="intakes/videos/"),
        ),
        migrations.AddField(
            model_name="animalintake",
            name="videos",
            field=models.FileField(blank=True, null=True, upload_to="animal_videos/"),
        ),
        migrations.AlterField(
            model_name="animalintake",
            name="animal_id",
            field=models.CharField(
                blank=True, editable=False, max_length=20, null=True, unique=True
            ),
        ),
    ]
