# Generated by Django 5.1.7 on 2025-03-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0006_animalintake_stay_history_medicalrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalrecord",
            name="vaccination",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Rabies", "Rabies"),
                    ("Distemper", "Distemper"),
                    ("Parvovirus", "Parvovirus"),
                    ("Bordetella", "Bordetella"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
