# Generated by Django 5.1.7 on 2025-03-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0008_appointment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("rescheduled", "rescheduled"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
