# Generated by Django 5.1.7 on 2025-03-26 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0011_healthstatusupdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="BehaviorAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observed_date", models.DateField()),
                ("temperament", models.CharField(max_length=100)),
                ("interaction_notes", models.TextField()),
                ("behavior_score", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_assessments",
                        to="animals.animal",
                    ),
                ),
                (
                    "observer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
