# Generated by Django 5.1.7 on 2025-03-26 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0014_trainingnote"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdoptionApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("date_of_birth", models.DateField()),
                (
                    "home_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("house", "House"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("owns_home", models.BooleanField()),
                ("landlord_permission", models.BooleanField(blank=True, null=True)),
                ("number_of_adults", models.IntegerField()),
                ("number_of_children", models.IntegerField()),
                ("allergies", models.TextField(blank=True, null=True)),
                ("work_schedule", models.CharField(max_length=100)),
                ("previous_pet_experience", models.TextField()),
                ("current_pets", models.TextField(blank=True, null=True)),
                (
                    "preferred_pet_type",
                    models.CharField(
                        choices=[("dog", "Dog"), ("cat", "Cat"), ("other", "Other")],
                        max_length=10,
                    ),
                ),
                ("preferred_breed_or_size", models.CharField(max_length=100)),
                ("preferred_age_range", models.CharField(max_length=100)),
                ("adoption_reason", models.TextField()),
                ("daily_care_plan", models.TextField()),
                ("vacation_care_plan", models.TextField()),
                (
                    "pet_care_budget",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("emergency_plan", models.TextField()),
                ("lifelong_care_commitment", models.BooleanField()),
                ("consent_home_visits", models.BooleanField()),
                ("understands_return_policy", models.BooleanField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
