# Generated by Django 5.1.7 on 2025-03-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0015_adoptionapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="adoptionapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="adoptionapplication",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
