# Generated by Django 5.1.7 on 2025-03-26 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0016_adoptionapplication_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchingTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pet_type", models.CharField(max_length=50)),
                ("activity_level", models.CharField(max_length=50)),
                ("home_environment", models.CharField(max_length=100)),
                ("has_children", models.BooleanField()),
                ("has_other_pets", models.BooleanField()),
                ("allergies", models.BooleanField(default=False)),
                ("preferred_size", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "adopter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
