# Generated by Django 5.1.7 on 2025-03-26 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0017_matchingtool"),
    ]

    operations = [
        migrations.AddField(
            model_name="adoptionapplication",
            name="agreement_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="adoption_agreements/"
            ),
        ),
        migrations.AddField(
            model_name="adoptionapplication",
            name="agreement_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AdoptionAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agreement_text", models.TextField()),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="agreements/pdfs/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="animals.animal"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
