# Generated by Django 5.1.7 on 2025-03-26 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0018_adoptionapplication_agreement_pdf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adoptionapplication",
            name="animal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="animals.animal",
            ),
        ),
    ]
