# Generated by Django 5.1.7 on 2025-03-26 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0019_adoptionapplication_animal"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostAdoptionFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("followup_date", models.DateTimeField()),
                (
                    "followup_type",
                    models.CharField(
                        choices=[
                            ("call", "Phone Call"),
                            ("visit", "Home Visit"),
                            ("email", "Email"),
                        ],
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="animals.animal"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
