# Generated by Django 5.1.7 on 2025-03-27 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0020_postadoptionfollowup"),
    ]

    operations = [
        migrations.CreateModel(
            name="FosterApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("has_other_pets", models.BooleanField()),
                ("pet_experience", models.TextField()),
                ("has_children", models.BooleanField()),
                ("home_type", models.CharField(max_length=100)),
                ("fenced_yard", models.BooleanField()),
                ("foster_duration_preference", models.CharField(max_length=100)),
                ("reason_for_fostering", models.TextField()),
                ("availability_start", models.DateField()),
                ("availability_end", models.DateField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
