# Generated by Django 5.1.7 on 2025-03-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0021_fosterapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="health_status",
            field=models.CharField(
                choices=[
                    ("healthy", "Healthy"),
                    ("needs_care", "Needs Care"),
                    ("critical", "Critical"),
                ],
                default="healthy",
                max_length=20,
            ),
        ),
    ]
