# Generated by Django 5.1.7 on 2025-03-27 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0024_fostercommunication"),
    ]

    operations = [
        migrations.CreateModel(
            name="LostPetReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pet_name", models.CharField(max_length=100)),
                ("species", models.CharField(max_length=50)),
                ("breed", models.CharField(blank=True, max_length=100)),
                ("color", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("last_seen_location", models.CharField(max_length=255)),
                ("last_seen_date", models.DateField()),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="lostpets/photos/"
                    ),
                ),
                ("contact_info", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lost_pet_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
