# Generated by Django 5.1.7 on 2025-03-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0025_lostpetreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="lostpetreport",
            name="name",
            field=models.CharField(default="Unnamed", max_length=100),
        ),
        migrations.AddField(
            model_name="lostpetreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("resolved", "Resolved"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
