# Generated by Django 5.1.7 on 2025-03-28 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0026_lostpetreport_name_lostpetreport_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoundAnimalReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("species", models.CharField(max_length=50)),
                ("breed", models.CharField(blank=True, max_length=100)),
                ("color", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("found_location", models.CharField(max_length=255)),
                ("found_date", models.DateField()),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="foundanimals/photos/"
                    ),
                ),
                ("contact_info", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("under_review", "Under Review"),
                            ("available", "Available"),
                            ("claimed", "Claimed"),
                        ],
                        default="under_review",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "finder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="found_animal_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
