# Generated by Django 5.1.7 on 2025-03-29 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0034_order_orderitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("intake", "Animal Intake"),
                            ("adoption", "Adoption"),
                            ("medical", "Medical Treatments"),
                            ("volunteer", "Volunteer Hours"),
                            ("financial", "Financial Data"),
                        ],
                        max_length=50,
                    ),
                ),
                ("parameters", models.JSONField()),
                (
                    "generated_file",
                    models.FileField(blank=True, null=True, upload_to="reports/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
