# Generated by Django 5.1.7 on 2025-03-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0035_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("staff", "Shelter Staff"),
                    ("vet", "Veterinarian"),
                    ("volunteer", "Volunteer"),
                    ("donor", "Donor"),
                ],
                default="volunteer",
                max_length=20,
            ),
        ),
    ]
