name: Build and Deploy Django App to Azure Web App

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect Static Files
        run: |
          python manage.py collectstatic --noinput

      - name: Run Migrations
        run: |
          python manage.py migrate

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: animal-shelter-webapp  # 👈 Your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
